apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: developer-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["deployments","services","cronjobs","jobs"]
  verbs: ["get", "watch", "list","create"]
  
- apiGroups: ["*"]
  resources: ["pods","pods/exec"]
  verbs: ["get","watch","list","delete","create"]
