kind: role
version: v4
metadata:
  name: devops-new
spec:
  options:
    forward_agent: true
  allow:
    cluster_labels:
      '*': '*'
    node_labels:
      'env': 'staging'
    logins:
    - devops
    - developer
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - event
      verbs:
      - list
      - read
  deny: {}