kind: role
version: v4
metadata:
  name: tiffany-developer
spec:
  allow:
    cluster_labels:
      'project': 'omni-saas-admin'
    node_labels:
      'env':
      - dev
      - qa
      - staging
    logins:
    - developer
    kubernetes_groups:
    - developer
    kubernetes_labels:
      'env': 'omnisaas'

  deny: {}