- name: create .kube directory
  file:
    path: /root/.kube
    state: directory

- name: upload k8s scripts
  copy:
    src: templates/scripts
    dest: /root/.kube/

- name: use scripts get-kubeconfig.sh generate kubeconfig
  shell: "cd /root/.kube &&  sh /root/.kube/scripts/get-kubeconfig.sh"

- name: upload k8s developer role directory
  copy: 
    src: templates/role
    dest: /root/.kube/

- name: create k8s developer sa && clusterrole && clusterolebinding
   shell: "kubectl create sa developer -n teleport && kubectl create -f /root/.kube/role/developer-clusteerrole.yaml && kubectl create -f /root/.kube/role/developer-clusterrolebind.yaml"

- name: create k8s devops sa && clusterrole && clusterolebinding
   shell: "kubectl create sa devops -n teleport && kubectl create -f /root/.kube/role/devops-clusteerrole.yaml && kubectl create -f /root/.kube/role/devops-clusterrolebind.yaml"
  