---
# tasks file for wcl-zabbix-custom-scripts
- name: Copy each zabbix custom script to correct location.
  copy: src={{ item }} dest=/usr/lib/zabbix/scripts/ owner=root mode=755
  with_fileglob:
    - zabbix-scripts/scripts/*

- name: Copy userparameter configuration files to correct location.
  copy: src={{ item }} dest=/etc/zabbix/zabbix_agentd.d/
  with_fileglob:
    - zabbix-scripts/userparameters/*
  notify:
    - restart zabbix-agent
