---
- src: https://github.com/dj-wasabi/ansible-zabbix-proxy.git
  name: zabbix-proxy
  version: master

- src: https://github.com/dj-wasabi/ansible-zabbix-agent
  name: zabbix-agent
  version: master

- src: https://github.com/wiredcraft-ops/role-wcl-common.git
  name: wcl-common
  version: master
