---
# tasks file for zabbix-scripts
- name: generate script to proper location
  template: src=../templates/slack_zabbix.py.j2 dest=/usr/lib/zabbix/alertscripts/slack_zabbix_{{ itme.name }}.py
  with_items:
    - {name: 'wcl', slack_url: https://hooks.slack.com/services/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}
    - {name: 'sbux', slack_url: https://hooks.slack.com/services/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}

- name: change config zabbix_server.conf
  linefile: dest=/etc/zabbix/zabbix_server.conf regexp="^AlertScriptsPath=" line="AlertScriptsPath=/usr/lib/zabbix/alertscripts"

- name: mkdir log folder
- file: path=/var/log/zabbix state=directory mode=0755 owner=zabbix group=zabbix
