---
- name: debug variable
  hosts: all
  become: yes
  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ project }} has gateway {{ client_secret }}