---
- name: update root-cluster and all leaf-cluster roles
  hosts: role
  become: yes
  vars_prompt:
    - name: role_name
      prompt: "Which roles you want to apply(input 'all' to apply all roles):\n\n{{ lookup('fileglob', 'templates/public/roles/*.yaml', wantlist=True) | map('basename') | join('\n')}}\n"
      private: false

  tasks:
    - name: distribution the specified Role.
      block:
        - copy:
            src: templates/public/roles/{{ role_name }}
            dest: /etc/teleport.d/roles/{{ role_name }}
        - shell: 
            "ls /etc/teleport.d/roles/{{ role_name }}"
          register: role_list
        - debug:
            var: role_list.stdout_lines
        - shell: 
            "/usr/local/bin/tctl create -f /etc/teleport.d/roles/{{ role_name }}"
      when: role_name != 'all'

    - name: distribution all of the  roles.
      block:
        - copy:
            src: templates/public/roles
            dest: /etc/teleport.d/
        - shell: 
            "ls /etc/teleport.d/roles/*.yaml"
          register: role_list
        - debug:
            var: role_list.stdout_lines
        - shell: 
            "/usr/local/bin/tctl create -f {{ item }}"
          loop: "{{ role_list.stdout_lines }}"
      when: role_name == 'all'
