---
- name: Modify sshd_config
  hosts: teleport
  become: yes
  tasks:
    - name: disable root login
      lineinfile: 
        path: '/etc/ssh/sshd_config'
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'      
      notify: 'restart sshd'

    - name: disable password auth
      lineinfile: 
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
      notify: 'restart sshd'

    - name: modify ssh port to 40022
      lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^#Port 22'
        line: 'Port 40022'
      notify: 'restart sshd'

  handlers: 
    - name: 'restart sshd'
      service: 
        name: sshd
        state: restarted

- name: Yum install some necessary software
  hosts: teleport
  become: yes
  tasks:
    - name: install pkgs
      yum: 
        name: tar 
        state: present
