---
- name: access kubernetes
  hosts: omni-saas-admin
  become: yes
  vars_prompt:
    - name: k8sconfigfile
      prompt: 'could you generated k8s config at /root/.kube/config? [yes / no]'
      default: 'no'
      private: false

  roles:
    - role: kubernetes 
      when: k8sconfigfile == 'yes'

  tasks:
    - name: Generating Configuration File
      block:
        - template:
            src: leaf-cluster/teleport.yaml
            dest: /etc/teleport.yaml
        - template:
            src: leaf-cluster/teleport.service
            dest: /usr/lib/systemd/system/teleport.service
        - systemd:
            name: teleport
            state: restarted
            enabled: yes
            daemon_reload: yes
      when: k8sconfigfile == 'yes'