---
- name: teleport root cluster admin
  hosts: root-cluster-admin
  become: yes
  tasks:
    - name: create user devops/developer and upload devops sudo file
      block:
        - user:
            name: devops
            groups: systemd-journal
            state: present
        - user:
            name: developer
            groups: systemd-journal
            state: present
        - template:
            src: public/sudo/devops
            dest: /etc/sudoers.d/
      tags: sudo
      
    - name: download and install the teleport 
      block:
        - file:
            path: /download
            state: directory
        - get_url:
            url: https://wcl-download.sh1a.qingstor.com/teleport-{{ teleport_version }}-linux-amd64-bin.tar.gz
            #url: https://get.gravitational.com/teleport-{{ teleport_version }}-linux-amd64-bin.tar.gz 
            dest: /download/teleport-{{ teleport_version }}-linux-amd64-bin.tar.gz
            validate_certs: no
        - unarchive:
            src: /download/teleport-{{ teleport_version }}-linux-amd64-bin.tar.gz
            dest: "/tmp/"
            remote_src: yes
        - copy:
            remote_src: yes
            src: "/tmp/teleport/{{ item }}"
            dest: /usr/local/bin
            mode: 755
          with_items:
            - teleport
            - tctl
            - tsh
        - file:
            path: /etc/teleport.d
            state: directory
     tags: install

    - name: Generating  Configuration File
      block:
        - template:
            src: root-cluster/teleport.yaml
            dest: /etc/teleport.yaml
        - template:
            src: root-cluster/teleport.service
            dest: /usr/lib/systemd/system/teleport.service
        - systemd:
            name: teleport
            state: restarted
            enabled: yes
            daemon_reload: yes
      tags: config

    - name: generate aws credentials
      block:
        - file:
            path: /root/.aws
            state: directory
        - template:
            src: root-cluster/aws/credentials
            dest: /root/.aws/credentials
      tags: aws
