---
- name: Download or Update/Install Teleport for agent
  hosts: bby-staging
  become: yes
  vars_prompt:
    - name: agent_token
      #Run this command on the leaf-cluster admin server to generate the token
      prompt: 'tctl tokens add --type=node --ttl=30m <enter node token>'
      private: false

    - name: labels_env
      prompt: 'pls labels env[make sure your hosts is corresponding]: <e.g. dev, staging, pre-prod, prod>'
      private: false

    - name: labels_project
      prompt: 'pls labels project: <e.g. project1, blue, red>'
      private: false

    - name: leaf_admin_ip
      prompt: 'pls enter your project admin server internal ip'
      default: '127.0.0.1'
      private: false

    - name: jump_server
      prompt: 'pls enter your project admin server ssh name'
      private: false

  vars:
    ansible_ssh_common_args: ' -o StrictHostKeyChecking=accept-new -o ProxyCommand="ssh -W %h:%p -q {{ jump_server }}"'
    ansible_user: wcladmin
        
  tasks:
    - name: create user devops/developer and upload devops sudo file
      block:
        - group:
            name: docker
            state: present
        - user:
            name: devops
            groups: systemd-journal,docker
            state: present
            append: yes
        - user:
            name: developer
            groups: systemd-journal,docker
            state: present
            append: yes
        - template:
            src: agent/devops
            dest: /etc/sudoers.d/
      tags: sudo

    #Teleport source files are downloaded when leaf-Cluster is initialized, so use them directly.
    - name: Copy teleport.tar.gz from leaf-admin server and install teleport
      block:
        - file:
            path: /download
            state: directory
        - get_url:
            url: https://wcl-download.sh1a.qingstor.com/teleport-{{ teleport_version }}-linux-amd64-centos7-bin.tar.gz
            dest: /download/
            validate_certs: no
        - unarchive:
            src: /download/teleport-{{ teleport_version }}-linux-amd64-centos7-bin.tar.gz
            dest: /tmp/
            remote_src: yes
        - copy:
            remote_src: yes
            src: "/tmp/teleport/{{ item }}"
            dest: /usr/local/bin
            mode: 755
          with_items:
            - teleport
            - tctl
            - tsh
        - file:
            path: /tmp/teleport
            state: absent
        - file:
            path: /etc/teleport.d
            state: directory
      tags: install

    - name: Generate teleport config
      block: 
        - template:
            src: agent/teleport.yaml
            dest: /etc/teleport.yaml
        - template:
            src: agent/teleport.service
            dest: /usr/lib/systemd/system/teleport.service
      tags: config
    
    - name: restart teleport
      systemd:
        name: teleport
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags: restart
