---
- hosts: zabbix.service.wiredcraft.com
  user: root
  roles: 
    - role: wcl-common

    - role: Rackspace_Automation.mysql
      mysql_root_password: changeme123

    # Zabbix Server
    - role: dj-wasabi.zabbix-server
      zabbix_url: zabbix.service.wiredcraft.com
      database_type: mysql
      database_type_long: mysql

    # Enable agent 
    - role: dj-wasabi.zabbix-agent
      agent_server: "127.0.0.1"

    - role: wcl-zabbix-scripts
      zabbix_scripts:
        - server
        - agent