#!/usr/bin/env bash

set -euxo pipefail

# Set working directory to the script directory
cd "$(dirname "$0")"
# Create reports directory
mkdir -p reports
rm -rf reports/*

# Default billing cycle to last month, alternatively set it in $1.
billing_cycle=${1:-$(date --date 'last month' +'%Y-%m')}
report_json=reports/billing_data_$billing_cycle.json
report_csv=reports/billing_data_$billing_cycle.csv
report_html=reports/billing_data_$billing_cycle.html

# Paging
# Set page size to max (300)
page_size=300
page_num=1
continue=true

# Fetch data
while [ "$continue" = true ]; do
  paged_json=reports/instance-bill-page-$page_num.json

  aliyun bssopenapi QuerySplitItemBill \
    --BillingCycle "$billing_cycle" \
    --PageSize "$page_size" \
    --PageNum "$page_num" \
    > "$paged_json"

  ((page_num+=1))
  continue=$(jq '.Data.PageNum * .Data.PageSize < .Data.TotalCount' "$paged_json")
done

# Merge results of all pages and do processing
jq -s 'map(.Data.Items.Item)|add' reports/instance-bill-*.json \
  | jq -f billing-by-tags-and-products.jq > "$report_json"

# Generate html and CSV report
mustache "$report_json" billing-report.html.mustache > "$report_html"
mustache "$report_json" billing-report.csv.mustache > "$report_csv"
