---
# tasks file for wcl-zabbix-custom-scripts
- name: Copy each zabbix custom script to correct location.
  copy: src={{ item }} dest=/usr/lib/zabbix/scripts/ owner=root mode=755
  with_fileglob:
    - zabbix-scripts/scripts/*

- name: Copy userparameter configuration files to correct location.
  copy: src={{ item }} dest=/etc/zabbix/zabbix_agentd.d/
  with_fileglob:
    - zabbix-scripts/userparameters/*

- name: check if zabbix-agent is installed.
  stat:
    path=/etc/init.d/zabbix-agent
  register: service_status

- name: restart zabbix-agent if installed.
  service:
    name=zabbix-agent
    state=restarted
  when: service_status.stat.exists == True