---
- hosts: registry-us:builder
  roles:
    - role: wcl-docker
      docker_users:
        - wcladmin

- hosts: registry-cn
  roles:
    - role: wcl-docker
      docker_registry_mirror_url: "{{ _docker_registry_mirror_url }}"
      pip_enable_douban_mirror: true
      docker_users:
        - wcladmin