---
- hosts: pipelines
  tasks:
    - name: Login wiredcraft registry
      docker_login:
        registry: "{{ wiredcraft_registry }}"
        username: "{{ wiredcraft_registry_deploy_user }}"
        password: "{{ wiredcraft_registry_deploy_pass }}"

    - set_fact:
        pipelines_name: "pipelines-0"

    - name: Start {{ pipelines_name }}
      docker_container:
        name: "{{ pipelines_name }}"
        image: "{{ wiredcraft_registry }}/wiredcraft/pipelines:latest"
        status: started
        pull: true
        restart: true
        restart_policy: always
        hostname: "{{ pipelines_name }}"
        ports:
          - "8888:8888"
        volumes:
          - /opt/{{ pipelines_name }}/workspace:/workspace
          - /opt/{{ pipelines_name }}/data:/data
          - /opt/{{ pipelines_name }}/id_rsa:/home/pipelines/.ssh/id_rsa:ro