---
# Add the container
- include: setup-pipelines.yml pipelines_name=pipelines-0

# Ensure the SSH key is known
- hosts: pipelines
  tasks:
    # TODO - replace by fetching the http://pipeline/keys instead
    - name: Get the public key of pipelines from pipelines-0
      command: cat /opt/pipelines-0/id_rsa.pub
      register: ssh_admin_pub

    - name: Add keys to wcladmin
      authorized_key:
        user: wcladmin
        key: "{{ ssh_admin_pub.stdout }}"

