---
- hosts: pipelines
  tasks:
    - name: Create volumes for container
      file:
        name: /opt/{{ pipelines_name }}/{{ item }}
        state: directory
        owner: 999
        group: 999
      with_items:
        - workspace
        - data
        - home

    - name: Create extra volumes for container (k8s)
      file:
        name: /opt/{{ pipelines_name }}/home/{{ item }}
        state: directory
        owner: 999
        group: 999
      with_items:
        - .config
        - .kube

    - name: Create private SSH key for container
      user: 
        name: root
        generate_ssh_key: yes
        ssh_key_file: /opt/{{ pipelines_name }}/id_rsa
        ssh_key_comment: 'SSH key for pipelines {{ pipelines_name }}'

    - name: Change Ownership of the SSH key to belong to pipelines (999:999)
      file:
        name: /opt/{{ pipelines_name }}/{{ item }}
        owner: 999
        group: 999
      with_items:
        - id_rsa
        - id_rsa.pub

    - name: Start {{ pipelines_name }}
      docker_container:
        name: "{{ pipelines_name }}"
        image: "{{ docker_registry }}/pipelines:latest"
        state: started
        pull: true
        restart: true
        restart_policy: always
        hostname: "{{ pipelines_name }}"
        ports:
          - "8888:8888"
        env:
          ADMIN_PASS: '{{ pipelines_admin_pass }}'
        volumes:
          - /opt/{{ pipelines_name }}/workspace:/workspace
          - /opt/{{ pipelines_name }}/data:/data
          - /opt/{{ pipelines_name }}/home/.config:/home/pipelines/.config
          - /opt/{{ pipelines_name }}/home/.kube:/home/pipelines/.kube
          - /opt/{{ pipelines_name }}/id_rsa:/home/pipelines/.ssh/id_rsa:ro
          - /opt/{{ pipelines_name }}/id_rsa.pub:/home/pipelines/.ssh/id_rsa.pub:ro
