---
- hosts: pipelines
  pre_tasks:
    - name: Prepare SSL certs folder
      file:
        name: /opt/certs
        state: directory

    - name: Copy SSL key and crt files
      copy: 
        src: ssl/{{ item }}
        dest: /opt/certs/{{ item }}
      with_items:
        - server.key
        - server.crt

  roles:
    - role: wcl-nginx
      nginx_user: "nginx"
      nginx_group: "nginx"
      nginx_http_params:
        - sendfile on
        - server_tokens off
        - access_log /var/log/nginx/access.log
        - error_log /var/log/nginx/error.log
        - types_hash_max_size 2048
        - server_names_hash_bucket_size 64
        - gzip on
        - gzip_disable msie6
        - gzip_proxied any
        - gzip_comp_level 6
        - gzip_buffers 16 8k
        - gzip_http_version 1.1
        - gzip_types text/plain text/css application/json application/x-javascript application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml

      nginx_sites:
        pipelines:
          - listen 0.0.0.0:80
          - listen 0.0.0.0:443 ssl
          - if ($scheme = 'http') { rewrite https://$host/$uri 301; }
          - port_in_redirect off
          - set $pipelines bad
          - if ($host = "pipelines.{{ service_domain }}") { set $pipelines admin; }
          - if ($host ~ "^pipelines-(.*)\.{{ service_domain | replace('.', '\.') }}$") { set $pipelines $1; }
          - if ($pipelines = 'bad') {return 404;}
          - location /key { root /opt/$pipelines; add_header Content-Type text/plain; rewrite ^ /id_rsa.pub break; }
          - location / { proxy_pass http://$pipelines; }

      nginx_configs:
        ssl:
          - ssl_certificate_key /opt/certs/server.key
          - ssl_certificate /opt/certs/server.crt

        upstream:
          - upstream admin { server {{ ansible_default_ipv4.address }}:8888; }
