---
- hosts: pipelines
  roles:
    - role: wcl-docker
      docker_users:
        - wcladmin
  tasks:
    - name: Setup credentials to pull images
      docker_login:
        username: "{{ docker_user_deploy }}"
        password: "{{ docker_pass_deploy }}"
        registry: "{{ docker_registry }}"
#