name: Build and Push landing page image

on:
  push:
    branches:
      - master
    paths:
      - services/landing-page/**
  pull_request:
    paths:
      - services/landing-page/**
  workflow_dispatch:
    inputs:
      tag:
        description: Docker image tag
        required: true
        default: latest

jobs:
  build-push-image:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      -
        name: Checkout assets images
        run: |
            git worktree add -B assets-images-for-landing-page \
              services/landing-page/themes/devops-landing-page/static/assets/images \
              origin/assets-images-for-landing-page
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.HARBOR_CN }}/internal/landing-page
          # v1.x.x-landing-page -> v1.x.x
          tags: |
            type=edge
            type=match,pattern=(v.+)-landing-page,group=1
            type=raw,value=${{ github.event.inputs.tag }}
            type=ref,event=pr
      -
        name: Login to Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_CN }}
          username: ${{ secrets.HARBOR_GH_ACTIONS_USERNAME }}
          password: ${{ secrets.HARBOR_CN_GH_ACTIONS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/landing-page
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
